### ISSUE TITLE
Two same browser options in menu

### ISSUE THREAD

**Issue by Edfgdz** [tasomaniac/OpenLinkWith#38]
There are two browser options in menu which are as same as each other.

Can you fix this problem?

![img_20180610_201409](https://user-images.githubusercontent.com/26460124/41201508-f7fb0d58-6ceb-11e8-8c15-cbe42b732c30.png)

**Comment by tasomaniac** [comment]
Seems like something I can fix. Thanks for the report. I will reach you out for possible testing. Thanks.

**Comment by tasomaniac** [comment]
This problem should be fixed with the latest update. Can you send another
screenshot from the latest version?

Thanks.

**Comment by Edfgdz** [comment]
I find this still not work for system default browser.

![img_20180907_195429](https://user-images.githubusercontent.com/26460124/45217805-16e2b080-b26b-11e8-905f-6272843fa543.png)
